"""Registry of employers with VERIFIED public ATS boards (Tier 2).

All tokens below returned live jobs when last checked. Spans tech, quant/trading,
biotech/health, consumer, fintech, education and consulting so the tool surfaces
internships across disciplines — not just software.

Add more: confirm at https://boards-api.greenhouse.io/v1/boards/<token>/jobs
"""
from __future__ import annotations

GREENHOUSE = [
    {"name": "Affirm", "ats_token": "affirm", "is_quant_target": False},
    {"name": "Airbnb", "ats_token": "airbnb", "is_quant_target": False},
    {"name": "Airtable", "ats_token": "airtable", "is_quant_target": False},
    {"name": "Akunacapital", "ats_token": "akunacapital", "is_quant_target": True},
    {"name": "Anthropic", "ats_token": "anthropic", "is_quant_target": False},
    {"name": "AppLovin", "ats_token": "applovin", "is_quant_target": False},
    {"name": "Archer", "ats_token": "archer", "is_quant_target": False},
    {"name": "Asana", "ats_token": "asana", "is_quant_target": False},
    {"name": "Boston Consulting Group", "ats_token": "bcg", "is_quant_target": False},
    {"name": "Block", "ats_token": "block", "is_quant_target": False},
    {"name": "Brex", "ats_token": "brex", "is_quant_target": False},
    {"name": "Calm", "ats_token": "calm", "is_quant_target": False},
    {"name": "CarGurus", "ats_token": "cargurus", "is_quant_target": False},
    {"name": "Chime", "ats_token": "chime", "is_quant_target": False},
    {"name": "Cloudflare", "ats_token": "cloudflare", "is_quant_target": False},
    {"name": "Coinbase", "ats_token": "coinbase", "is_quant_target": False},
    {"name": "Coursera", "ats_token": "coursera", "is_quant_target": False},
    {"name": "Databricks", "ats_token": "databricks", "is_quant_target": False},
    {"name": "Datadog", "ats_token": "datadog", "is_quant_target": False},
    {"name": "Discord", "ats_token": "discord", "is_quant_target": False},
    {"name": "Duolingo", "ats_token": "duolingo", "is_quant_target": False},
    {"name": "Elastic", "ats_token": "elastic", "is_quant_target": False},
    {"name": "Fastly", "ats_token": "fastly", "is_quant_target": False},
    {"name": "Figma", "ats_token": "figma", "is_quant_target": False},
    {"name": "Flatiron Health", "ats_token": "flatironhealth", "is_quant_target": False},
    {"name": "Flexport", "ats_token": "flexport", "is_quant_target": False},
    {"name": "Flowtraders", "ats_token": "flowtraders", "is_quant_target": True},
    {"name": "Formlabs", "ats_token": "formlabs", "is_quant_target": False},
    {"name": "Ginkgo Bioworks", "ats_token": "ginkgobioworks", "is_quant_target": False},
    {"name": "GitLab", "ats_token": "gitlab", "is_quant_target": False},
    {"name": "Grafana Labs", "ats_token": "grafanalabs", "is_quant_target": False},
    {"name": "Gusto", "ats_token": "gusto", "is_quant_target": False},
    {"name": "Hometap", "ats_token": "hometap", "is_quant_target": False},
    {"name": "IMC Trading", "ats_token": "imc", "is_quant_target": True},
    {"name": "Instacart", "ats_token": "instacart", "is_quant_target": False},
    {"name": "Jump Trading", "ats_token": "jumptrading", "is_quant_target": True},
    {"name": "Khan Academy", "ats_token": "khanacademy", "is_quant_target": False},
    {"name": "Klaviyo", "ats_token": "klaviyo", "is_quant_target": False},
    {"name": "Lucid Motors", "ats_token": "lucidmotors", "is_quant_target": False},
    {"name": "Lyft", "ats_token": "lyft", "is_quant_target": False},
    {"name": "Marqeta", "ats_token": "marqeta", "is_quant_target": False},
    {"name": "Mercury", "ats_token": "mercury", "is_quant_target": False},
    {"name": "MongoDB", "ats_token": "mongodb", "is_quant_target": False},
    {"name": "New Relic", "ats_token": "newrelic", "is_quant_target": False},
    {"name": "Nuro", "ats_token": "nuro", "is_quant_target": False},
    {"name": "Old Mission Capital", "ats_token": "oldmissioncapital", "is_quant_target": True},
    {"name": "Oura", "ats_token": "oura", "is_quant_target": False},
    {"name": "PDT Partners", "ats_token": "pdtpartners", "is_quant_target": True},
    {"name": "Peloton", "ats_token": "peloton", "is_quant_target": False},
    {"name": "Pinterest", "ats_token": "pinterest", "is_quant_target": False},
    {"name": "Recursion Pharmaceuticals", "ats_token": "recursionpharmaceuticals", "is_quant_target": False},
    {"name": "Reddit", "ats_token": "reddit", "is_quant_target": False},
    {"name": "Robinhood", "ats_token": "robinhood", "is_quant_target": False},
    {"name": "Roblox", "ats_token": "roblox", "is_quant_target": False},
    {"name": "Samsara", "ats_token": "samsara", "is_quant_target": False},
    {"name": "Scale AI", "ats_token": "scaleai", "is_quant_target": False},
    {"name": "SimpliSafe", "ats_token": "simplisafe", "is_quant_target": False},
    {"name": "Stripe", "ats_token": "stripe", "is_quant_target": False},
    {"name": "Sumo Logic", "ats_token": "sumologic", "is_quant_target": False},
    {"name": "The Trade Desk", "ats_token": "thetradedesk", "is_quant_target": False},
    {"name": "Toast", "ats_token": "toast", "is_quant_target": False},
    {"name": "TransMarket Group", "ats_token": "transmarketgroup", "is_quant_target": True},
    {"name": "Twitch", "ats_token": "twitch", "is_quant_target": False},
    {"name": "Vatic Labs", "ats_token": "vaticlabs", "is_quant_target": True},
    {"name": "Verkada", "ats_token": "verkada", "is_quant_target": False},
    {"name": "Virtu", "ats_token": "virtu", "is_quant_target": True},
    {"name": "Walleye Capital", "ats_token": "walleyecapital-external-students", "is_quant_target": True},
    {"name": "Waymo", "ats_token": "waymo", "is_quant_target": False},
    {"name": "Weiss Asset Management", "ats_token": "weissassetmanagement", "is_quant_target": True},
    # Northeast additions (verified live 2026-09)
    {"name": "DRW", "ats_token": "drweng", "is_quant_target": True},
    {"name": "Point72", "ats_token": "point72", "is_quant_target": True},
    {"name": "Jane Street", "ats_token": "janestreet", "is_quant_target": True},
    {"name": "Tower Research Capital", "ats_token": "towerresearchcapital", "is_quant_target": True},
    {"name": "AQR", "ats_token": "aqr", "is_quant_target": True},
    {"name": "Schonfeld", "ats_token": "schonfeld", "is_quant_target": True},
    {"name": "Squarespace", "ats_token": "squarespace", "is_quant_target": False},
    {"name": "Betterment", "ats_token": "betterment", "is_quant_target": False},
    {"name": "Oscar Health", "ats_token": "oscar", "is_quant_target": False},
    {"name": "FanDuel", "ats_token": "fanduel", "is_quant_target": False},
    {"name": "Justworks", "ats_token": "justworks", "is_quant_target": False},
    {"name": "Cockroach Labs", "ats_token": "cockroachlabs", "is_quant_target": False},
    {"name": "Yext", "ats_token": "yext", "is_quant_target": False},
    {"name": "Zocdoc", "ats_token": "zocdoc", "is_quant_target": False},
    {"name": "Harry's", "ats_token": "harrys", "is_quant_target": False},
    {"name": "Glossier", "ats_token": "glossier", "is_quant_target": False},
    {"name": "SeatGeek", "ats_token": "seatgeek", "is_quant_target": False},
    {"name": "Attentive", "ats_token": "attentive", "is_quant_target": False},
    {"name": "CLEAR", "ats_token": "clear", "is_quant_target": False},
    {"name": "C3 AI", "ats_token": "c3iot", "is_quant_target": False},
    {"name": "PathAI", "ats_token": "pathai", "is_quant_target": False},
    {"name": "Markforged", "ats_token": "markforged", "is_quant_target": False},
    {"name": "Harvard Business School", "ats_token": "hbs", "is_quant_target": False},
    {"name": "Tripadvisor", "ats_token": "tripadvisor", "is_quant_target": False},
    {"name": "Cybereason", "ats_token": "cybereason", "is_quant_target": False},
]

LEVER = [
    # Verify at https://api.lever.co/v0/postings/<token>?mode=json before adding.
]

# Tier 4 watchlist: firms on their own portals (no public ATS API).
QUANT_WATCHLIST = [
    {"name": "Citadel / Citadel Securities", "careers_url": "https://www.citadel.com/careers/students/"},
    {"name": "Jane Street", "careers_url": "https://www.janestreet.com/join-jane-street/"},
    {"name": "Hudson River Trading", "careers_url": "https://www.hudsonrivertrading.com/careers/"},
    {"name": "Two Sigma", "careers_url": "https://careers.twosigma.com/careers/Students"},
    {"name": "DE Shaw", "careers_url": "https://www.deshaw.com/careers"},
    {"name": "DRW", "careers_url": "https://drw.com/work-at-drw"},
    {"name": "Optiver", "careers_url": "https://optiver.com/working-at-optiver/career-opportunities/"},
    {"name": "SIG (Susquehanna)", "careers_url": "https://careers.sig.com/"},
    {"name": "XTX Markets", "careers_url": "https://www.xtxmarkets.com/careers/"},
    {"name": "Tower Research", "careers_url": "https://www.tower-research.com/open-positions/"},
    {"name": "Five Rings", "careers_url": "https://www.fiverings.com/careers"},
    {"name": "Arrowstreet Capital", "careers_url": "https://www.arrowstreetcapital.com/careers/"},
]


# Ashby / Workday / SmartRecruiters seeds. Discovery (discover.py) adds hundreds more
# from apply URLs automatically; these just guarantee a few boards from day one.
ASHBY = [
    {"name": "Ramp", "ats_token": "ramp", "is_quant_target": False},
    {"name": "OpenAI", "ats_token": "openai", "is_quant_target": False},
    {"name": "Notion", "ats_token": "notion", "is_quant_target": False},
    {"name": "Linear", "ats_token": "linear", "is_quant_target": False},
    {"name": "Hex", "ats_token": "hex", "is_quant_target": False},
    {"name": "Plaid", "ats_token": "plaid", "is_quant_target": False},
    {"name": "Cursor", "ats_token": "cursor", "is_quant_target": False},
    {"name": "Replit", "ats_token": "replit", "is_quant_target": False},
    {"name": "Vanta", "ats_token": "vanta", "is_quant_target": False},
    {"name": "Modal", "ats_token": "modal", "is_quant_target": False},
    {"name": "Perplexity", "ats_token": "perplexity", "is_quant_target": False},
    {"name": "Cohere", "ats_token": "cohere", "is_quant_target": False},
    {"name": "Sierra", "ats_token": "sierra", "is_quant_target": False},
    {"name": "Harvey", "ats_token": "harvey", "is_quant_target": False},
    {"name": "Runway", "ats_token": "runway", "is_quant_target": False},
    {"name": "ElevenLabs", "ats_token": "elevenlabs", "is_quant_target": False},
    {"name": "Benchling", "ats_token": "benchling", "is_quant_target": False},
    {"name": "Watershed", "ats_token": "watershed", "is_quant_target": False},
]
WORKDAY = [
    {"name": "Moderna", "ats_token": "modernatx|wd1|M_tx", "is_quant_target": False},
]
SMARTRECRUITERS = [
    {"name": "Bosch", "ats_token": "BoschGroup", "is_quant_target": False},
]

# Sector employers (health, government, arts, ...): each entry also has "sector".
TALEO: list = []
ADP: list = []
JOBVITE: list = []

# --- sector seeds (generated by merge_sectors.py) ---
ADP += [
    {'name': 'Greater Boston Food Bank', 'ats_token': 'c8a69c17-a9c1-45ff-8324-98137a9b6b4d', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Mass Audubon', 'ats_token': '6044bc19-19e6-443a-8a51-62fe8af33798', 'is_quant_target': False, 'sector': 'nonprofit'},
]
GREENHOUSE += [
    {'name': "Sotheby's", 'ats_token': 'sothebys', 'is_quant_target': False, 'sector': 'arts_museums'},
    {'name': 'Khan Academy', 'ats_token': 'khanacademy', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Nexamp', 'ats_token': 'nexamp', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Peloton', 'ats_token': 'peloton', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'Axios', 'ats_token': 'axios', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Hearst', 'ats_token': 'hearst', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'NPR', 'ats_token': 'nationalpublicradioinc', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'ProPublica', 'ats_token': 'propublica', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Sony Music', 'ats_token': 'sonymusicentertainment', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'The New York Times', 'ats_token': 'thenewyorktimes', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Vox Media', 'ats_token': 'voxmedia', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Weber Shandwick', 'ats_token': 'webershandwick', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'WPP', 'ats_token': 'wpp', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'ACLU', 'ats_token': 'aclu', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Doctors Without Borders USA', 'ats_token': 'msfcareers', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Human Rights Watch', 'ats_token': 'humanrightswatch', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Robin Hood', 'ats_token': 'robinhood', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Southern Poverty Law Center', 'ats_token': 'southernpovertylawcenter', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Hasbro', 'ats_token': 'hasbro', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Unilever', 'ats_token': 'unilever', 'is_quant_target': False, 'sector': 'retail_consumer'},
]
JOBVITE += [
    {'name': 'Port Authority of New York and New Jersey', 'ats_token': 'panynj', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Feeding America', 'ats_token': 'feedingamerica', 'is_quant_target': False, 'sector': 'nonprofit'},
]
LEVER += [
    {'name': 'Planned Parenthood', 'ats_token': 'ppfa', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Spotify', 'ats_token': 'spotify', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Sierra Club', 'ats_token': 'sierraclub', 'is_quant_target': False, 'sector': 'nonprofit'},
]
ORACLE: list = []
ORACLE += [
    {'name': 'Pearson', 'ats_token': 'hccz.fa.em3.oraclecloud.com|CX_2', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Arcadis', 'ats_token': 'ebcs.fa.em2.oraclecloud.com|CX_1', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Stantec', 'ats_token': 'hdhl.fa.us6.oraclecloud.com|CX_1', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Honeywell', 'ats_token': 'ibqbjb.fa.ocs.oraclecloud.com|Honeywell', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Abt Global', 'ats_token': 'egpy.fa.us2.oraclecloud.com|JoinAbt', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Northwell Health', 'ats_token': 'eppr.fa.us2.oraclecloud.com|CX_2', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Fanatics', 'ats_token': 'fa-exki-saasfaprod1.fa.ocs.oraclecloud.com|CX_1', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'Hilton', 'ats_token': 'efet.fa.us2.oraclecloud.com|CX_1009', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'Marriott International', 'ats_token': 'ejwl.fa.us2.oraclecloud.com|CX', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'Chubb', 'ats_token': 'fa-ewgu-saasfaprod1.fa.ocs.oraclecloud.com|CX_2001', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Grant Thornton', 'ats_token': 'ehzq.fa.us2.oraclecloud.com|CX_1', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Hearst', 'ats_token': 'eevd.fa.us6.oraclecloud.com|CX_1', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Staples', 'ats_token': 'fa-exhh-saasfaprod1.fa.ocs.oraclecloud.com|StaplesInc', 'is_quant_target': False, 'sector': 'retail_consumer'},
]
SMARTRECRUITERS += [
    {'name': 'Harvard University', 'ats_token': 'HarvardUniversity', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'AECOM', 'ats_token': 'AECOM2', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Syngenta', 'ats_token': 'SyngentaGroup', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Veolia', 'ats_token': 'VeoliaEnvironnementSA', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'NBCUniversal', 'ats_token': 'NBCUniversal3', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Publicis Groupe', 'ats_token': 'publicisgroupe', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Oxfam America', 'ats_token': 'oxfamamerica2', 'is_quant_target': False, 'sector': 'nonprofit'},
]
TALEO += [
    {'name': 'Commonwealth of Massachusetts', 'ats_token': 'massanf|ex', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Hyatt', 'ats_token': 'hyatt|10780', 'is_quant_target': False, 'sector': 'hospitality_sports'},
]
WORKABLE: list = []
WORKABLE += [
    {'name': 'Cleveland Clinic', 'ats_token': 'cleveland-clinic', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'CVS Health', 'ats_token': 'cvshealth', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Northwell Health', 'ats_token': 'northwell-health', 'is_quant_target': False, 'sector': 'health'},
]
WORKDAY += [
    {'name': 'Etsy', 'ats_token': 'etsy|wd5|Etsy_Careers', 'is_quant_target': False, 'sector': 'arts_museums'},
    {'name': 'Argonne National Laboratory', 'ats_token': 'argonne|wd1|Argonne_Careers', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Argonne National Laboratory', 'ats_token': 'argonne|wd1|EDU_PUB', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Draper', 'ats_token': 'draper|wd5|draper_careers', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'HMH', 'ats_token': 'hmhw|wd12|hmh_careers', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'National Renewable Energy Laboratory', 'ats_token': 'nrel|wd5|nrel', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Northeastern University', 'ats_token': 'northeastern|wd1|careers', 'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Ameresco', 'ats_token': 'ameresco|wd5|Ameresco', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Corteva', 'ats_token': 'corteva|wd5|corteva', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': "Land O'Lakes", 'ats_token': 'landolakes|wd1|landolakes', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'ABB', 'ats_token': 'abb|wd3|external_career_page', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Analog Devices', 'ats_token': 'analogdevices|wd1|External', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Bose', 'ats_token': 'boseallaboutme|wd503|Bose_Careers', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Boston Dynamics', 'ats_token': 'bostondynamics|wd1|Boston_Dynamics', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'GE Aerospace', 'ats_token': 'geaerospace|wd5|ge_externalsite', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Johnson & Johnson', 'ats_token': 'jj|wd5|JJ', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Medtronic', 'ats_token': 'medtronic|wd1|medtroniccareers', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Medtronic', 'ats_token': 'medtronic|wd1|redeploymentmedtroniccareers', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Northrop Grumman', 'ats_token': 'ngc|wd1|northrop_grumman_external_site', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Northrop Grumman', 'ats_token': 'ngc|wd1|northrop_grumman_restricted_site', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Otis', 'ats_token': 'otis|wd5|REC_Ext_Gateway', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'RTX', 'ats_token': 'globalhr|wd5|Private_Posting_No_TMP', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'RTX', 'ats_token': 'globalhr|wd5|rec_rtx_ext_gateway', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Stanley Black & Decker', 'ats_token': 'sbdinc|wd1|Stanley_Black_Decker_Career_Site', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Booz Allen Hamilton', 'ats_token': 'bah|wd1|BAH_Jobs', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Federal Reserve Bank of Boston', 'ats_token': 'rb|wd5|FRS', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'MITRE', 'ats_token': 'mitre|wd5|MITRE', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Pew Research Center', 'ats_token': 'pewtrusts|wd5|TrustsExternal', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'RAND Corporation', 'ats_token': 'rand|wd5|External_Career_Site', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'Urban Institute', 'ats_token': 'urban|wd115|Urban-Careers', 'is_quant_target': False, 'sector': 'government_policy'},
    {'name': 'American Red Cross', 'ats_token': 'americanredcross|wd1|american_red_cross_careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Baystate Health', 'ats_token': 'baystatehealth|wd12|External_Careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Beth Israel Lahey Health', 'ats_token': 'bilh|wd1|External', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Biogen', 'ats_token': 'biibhr|wd3|external', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Boston Medical Center', 'ats_token': 'bmc|wd1|BMC', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Brown University Health', 'ats_token': 'brownhealth|wd12|External_Careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Cigna Group', 'ats_token': 'cigna|wd5|cignacareers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Cleveland Clinic', 'ats_token': 'ccf|wd1|ClevelandClinicCareers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'CVS Health', 'ats_token': 'cvshealth|wd1|CVS_Health_Careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'CVS Health', 'ats_token': 'cvshealth|wd1|Private_Postings_Intern_Conversion_ONLY', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Elevance Health', 'ats_token': 'elevancehealth|wd1|ELV-ET', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Mass General Brigham', 'ats_token': 'massgeneralbrigham|wd1|mgbexternal', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Memorial Sloan Kettering', 'ats_token': 'msk|wd108|MSKCC_Careers_Primary', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Moderna', 'ats_token': 'modernatx|wd1|M_tx', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'NewYork-Presbyterian', 'ats_token': 'nyp|wd1|nypcareers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Pfizer', 'ats_token': 'pfizer|wd1|PfizerCareers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Point32Health', 'ats_token': 'point32health|wd5|THP', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Takeda', 'ats_token': 'takeda|wd3|external', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Thermo Fisher Scientific', 'ats_token': 'thermofisher|wd5|ThermoFisherCareers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Tufts Medicine', 'ats_token': 'tuftsmedicine|wd1|Jobs', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'UMass Memorial Health', 'ats_token': 'ummh|wd1|Careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Vertex Pharmaceuticals', 'ats_token': 'vrtx|wd501|vertex_careers', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'Vertex Pharmaceuticals', 'ats_token': 'vrtx|wd501|vertex_intern', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'DraftKings', 'ats_token': 'draftkings|wd1|Campus_Career_Portal', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'DraftKings', 'ats_token': 'draftkings|wd1|Employee_Referral_Portal', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'MGM Resorts', 'ats_token': 'mgmresorts|wd5|MGMCareers', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'New Balance', 'ats_token': 'newbalance|wd1|careers', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'Nike', 'ats_token': 'nike|wd1|nke', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'The Walt Disney Company', 'ats_token': 'disney|wd5|disneycareer', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'The Walt Disney Company', 'ats_token': 'disney|wd5|disneycareerdc', 'is_quant_target': False, 'sector': 'hospitality_sports'},
    {'name': 'AIG', 'ats_token': 'aig|wd1|aig', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'AIG', 'ats_token': 'aig|wd1|early_careers', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Bank of America', 'ats_token': 'ghr|wd1|us-emplsv', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Fidelity Investments', 'ats_token': 'fmr|wd1|fidelitycareers', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Fidelity Investments', 'ats_token': 'fmr|wd1|targeted', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'RSM', 'ats_token': 'rsm|wd1|RSMCareers', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'State Street', 'ats_token': 'statestreet|wd1|equest', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'State Street', 'ats_token': 'statestreet|wd1|Global', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'The Hartford', 'ats_token': 'thehartford|wd5|Careers_External', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Vanguard', 'ats_token': 'vanguard|wd5|contractors_restricted', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Vanguard', 'ats_token': 'vanguard|wd5|vanguard_external', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Webster Bank', 'ats_token': 'websteronline|wd12|WebsterExternalCareerSite', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Wellington Management', 'ats_token': 'wellington|wd5|Campus', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Condé Nast', 'ats_token': 'condenast|wd5|CondeCareers', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Dow Jones', 'ats_token': 'dowjones|wd1|Dow_Jones_Career', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Edelman', 'ats_token': 'djeholdings|wd5|edelman-careers-E200', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'GBH', 'ats_token': 'publicmedia|wd1|WGBH_Careers', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'iHeartMedia', 'ats_token': 'iheartmedia|wd5|External_iHM', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Netflix', 'ats_token': 'netflix|wd1|Netflix', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Omnicom', 'ats_token': 'interpublic|wd5|omc', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'PBS', 'ats_token': 'vhr-pbs|wd5|PBSCareers', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Politico', 'ats_token': 'politico|wd108|POLITICO', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'The Atlantic', 'ats_token': 'atlanticmedia|wd1|Careers', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Thomson Reuters', 'ats_token': 'thomsonreuters|wd5|External_Career_Site', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Universal Music Group', 'ats_token': 'umusic|wd5|UMGUS', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Warner Bros. Discovery', 'ats_token': 'warnerbros|wd5|global', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Warner Music Group', 'ats_token': 'wmg|wd1|WMGUS', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Environmental Defense Fund', 'ats_token': 'osv-edf|wd5|Confidential', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Habitat for Humanity', 'ats_token': 'habitat|wd12|External', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'International Rescue Committee', 'ats_token': 'theirc|wd1|External_Careers', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'The Nature Conservancy', 'ats_token': 'nature|wd108|ExternalCareers', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Year Up', 'ats_token': 'yearup|wd503|YearUp', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': "BJ's Wholesale Club", 'ats_token': 'bjswholesaleclub|wd1|BJsCareers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Burlington', 'ats_token': 'burlington|wd5|BurlingtonCareers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'General Mills', 'ats_token': 'genmills|wd1|GMI_External_Careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Home Depot', 'ats_token': 'homedepot|wd5|careerdepot', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Home Depot', 'ats_token': 'homedepot|wd5|CareerDepotCanada', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Inspire Brands', 'ats_token': 'inspirebrands|wd5|InspireCareers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Kraft Heinz', 'ats_token': 'heinz|wd1|KraftHeinz_Careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Kraft Heinz', 'ats_token': 'heinz|wd1|KraftHeinz_Careers_UR', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'L.L.Bean', 'ats_token': 'llbean|wd1|LLBean_Careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': "Lowe's", 'ats_token': 'lowes|wd5|LWS_External_CS', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Ocean Spray', 'ats_token': 'oceanspray|wd5|OceanSprayJobs', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'PVH', 'ats_token': 'pvh|wd1|PVH_Careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Tapestry', 'ats_token': 'tapestry|wd108|Tapestry_Careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Target', 'ats_token': 'target|wd5|targetcareers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'The Coca-Cola Company', 'ats_token': 'coke|wd1|coca-cola-careers', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'TJX Companies', 'ats_token': 'tjx|wd1|TJX_EXTERNAL', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Unilever', 'ats_token': 'unilever|wd3|Unilever_Experienced_Professionals', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Walmart', 'ats_token': 'walmart|wd504|WalmartExternal', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'Walmart', 'ats_token': 'walmart|wd5|WalmartExternal', 'is_quant_target': False, 'sector': 'retail_consumer'},
]
# SuccessFactors tenants, every one checked live on 2026-09-17: the token is the whole host.
# These employers were already reaching students one job at a time through Google Jobs; seeding
# them reads the whole board instead.
SUCCESSFACTORS: list = [
    {'name': 'Qorvo', 'ats_token': 'careers.qorvo.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Corning', 'ats_token': 'corningjobs.corning.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Edison International', 'ats_token': 'apply.edisoncareers.com', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Entergy', 'ats_token': 'jobs.entergy.com', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'HF Sinclair', 'ats_token': 'careers.hfsinclair.com', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Westinghouse Electric Company', 'ats_token': 'careers.westinghousenuclear.com', 'is_quant_target': False, 'sector': 'energy_environment'},
    {'name': 'Advanced Energy', 'ats_token': 'jobs.advanced-energy.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Arkema', 'ats_token': 'jobs.arkema.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Commercial Metals Company', 'ats_token': 'jobs.cmc.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Epiroc', 'ats_token': 'www.careerprofile.epiroc.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Gulfstream Aerospace', 'ats_token': 'careers.gulfstream.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Huntington Ingalls Industries', 'ats_token': 'careers.huntingtoningalls.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Kodak', 'ats_token': 'careers.kodak.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'L3Harris Technologies', 'ats_token': 'jobs.l3harris.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Mitsubishi Heavy Industries America', 'ats_token': 'mhicareers.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Nucor', 'ats_token': 'jobs.nucor.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Paccar', 'ats_token': 'jobs.paccar.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'United Launch Alliance', 'ats_token': 'jobs.ulalaunch.com', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Zurich Insurance', 'ats_token': 'www.careers.zurich.com', 'is_quant_target': False, 'sector': 'insurance_finance'},
    {'name': 'Altice USA', 'ats_token': 'www.optimumcareers.com', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Hershey', 'ats_token': 'careers.thehersheycompany.com', 'is_quant_target': False, 'sector': 'retail_consumer'},
    {'name': 'W.W. Grainger', 'ats_token': 'jobs.grainger.com', 'is_quant_target': False, 'sector': 'retail_consumer'},
]

# Eightfold tenants, all five checked live on 2026-09-17. Four of them were already in our data one
# job at a time through Google Jobs; Micron came from probing, and it is also on Workday, which is
# fine - the same role from two sources collapses on the dedupe key and keeps both links.
# The token is the tenant, and where the employer's website is not <tenant>.com it is pinned after
# a pipe, because the Eightfold API requires it and answers 422 without it.
EIGHTFOLD: list = [
    {'name': 'John Deere', 'ats_token': 'johndeere', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Eaton', 'ats_token': 'eaton', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Micron Technology', 'ats_token': 'micron', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Boston Scientific', 'ats_token': 'bostonscientific', 'is_quant_target': False,
     'sector': 'health'},
    {'name': 'PayPal', 'ats_token': 'paypal', 'is_quant_target': False,
     'sector': 'insurance_finance'},
]


# iCIMS career sites on the employer's own host (sources/icims_site.py). These are every branded
# host our own listings already carried an "?icims=1" apply link for; all 29 answered /api/jobs
# when they were checked on 2026-09-18. Discovery adds more on its own, but only from a paid
# Google Jobs run, and the boards are free to scan, so they are named here rather than waited for.
ICIMS_SITE: list = [
    {'name': 'AMD', 'ats_token': 'careers.amd.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Johns Hopkins Applied Physics Laboratory', 'ats_token': 'careers.jhuapl.edu',
     'is_quant_target': False, 'sector': 'education_research'},
    {'name': 'Medpace', 'ats_token': 'careers.medpace.com', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'State Farm', 'ats_token': 'jobs.statefarm.com', 'is_quant_target': False,
     'sector': 'insurance_finance'},
    {'name': 'Clyde Companies', 'ats_token': 'careers.clydeinc.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Constellation Energy', 'ats_token': 'jobs.constellationenergy.com', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'Kinder Morgan', 'ats_token': 'careers.kindermorgan.com', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'Principal Financial Group', 'ats_token': 'careers.principal.com', 'is_quant_target': False,
     'sector': 'insurance_finance'},
    {'name': 'Post Holdings', 'ats_token': 'jobs.postholdings.com', 'is_quant_target': False,
     'sector': 'retail_consumer'},
    {'name': 'Garmin', 'ats_token': 'careers.garmin.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Keysight Technologies', 'ats_token': 'jobs.keysight.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Stryten', 'ats_token': 'jobs.stryten.com', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'Ulta Beauty', 'ats_token': 'careers.ulta.com', 'is_quant_target': False,
     'sector': 'retail_consumer'},
    {'name': 'Spirit AeroSystems', 'ats_token': 'careers.spiritaero.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'MSA Safety', 'ats_token': 'careers.msasafety.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'M.C. Dean', 'ats_token': 'careers.mcdean.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Exelon', 'ats_token': 'careers.comed.com', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'AARP', 'ats_token': 'careers.aarp.org', 'is_quant_target': False, 'sector': 'nonprofit'},
    {'name': 'Publicis Groupe', 'ats_token': 'careers.publicisgroupe.com', 'is_quant_target': False,
     'sector': 'media'},
    {'name': 'Arthur J. Gallagher & Co.', 'ats_token': 'jobs.ajg.com', 'is_quant_target': False,
     'sector': 'insurance_finance'},
    {'name': 'V2X', 'ats_token': 'careers.gov2x.com', 'is_quant_target': False,
     'sector': 'government_policy'},
    {'name': 'Sabre Systems', 'ats_token': 'careers.sabresystems.com', 'is_quant_target': False,
     'sector': 'government_policy'},
    {'name': 'BJC HealthCare', 'ats_token': 'jobs.bjc.org', 'is_quant_target': False, 'sector': 'health'},
    {'name': 'CDM Smith', 'ats_token': 'careers.cdmsmith.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Universal Health Services', 'ats_token': 'jobs.uhsinc.com', 'is_quant_target': False,
     'sector': 'health'},
    {'name': 'Planview', 'ats_token': 'careers.planview.com', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'FAST Enterprises', 'ats_token': 'careers.fastenterprises.com', 'is_quant_target': False,
     'sector': 'government_policy'},
    {'name': 'Cvent', 'ats_token': 'careers.cvent.com', 'is_quant_target': False,
     'sector': 'hospitality_sports'},
    {'name': 'Foundation Finance', 'ats_token': 'careers.foundationfinance.com', 'is_quant_target': False,
     'sector': 'insurance_finance'},
]


# JazzHR boards, the small-employer end of the market: one page holds the whole board, so a
# tenant costs a single request however many jobs it has. These are the tenants our own data
# already pointed at, resolved to the employer names JazzHR serves on the board - the subdomain
# is often not the company (neboagency is Nebo, aramcoservices is Aramco Americas).
JAZZHR: list = [
    {'name': 'Nebo', 'ats_token': 'neboagency', 'is_quant_target': False, 'sector': 'media'},
    {'name': 'Aramco Americas', 'ats_token': 'aramcoservices', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'Ragle Inc', 'ats_token': 'ragleinc', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Bee Sweet Citrus', 'ats_token': 'beesweetcitrus', 'is_quant_target': False,
     'sector': 'energy_environment'},
    {'name': 'ROUSH', 'ats_token': 'roush', 'is_quant_target': False, 'sector': 'engineering_manufacturing'},
    {'name': 'Aerotech', 'ats_token': 'aerotech', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Nova-Tech Engineering', 'ats_token': 'novatechengineering', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Engenious Design', 'ats_token': 'engeniousdesign', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Rantec Power Systems', 'ats_token': 'rantecpowersystemsinc', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Foxconn Industrial Internet', 'ats_token': 'foxconnggroup', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'DEKA Research & Development', 'ats_token': 'deka', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'Advanced Robotics for Manufacturing', 'ats_token': 'arminstitute', 'is_quant_target': False,
     'sector': 'engineering_manufacturing'},
    {'name': 'National Reconnaissance Office', 'ats_token': 'nro', 'is_quant_target': False,
     'sector': 'government_policy'},
    {'name': 'Innovation Works', 'ats_token': 'innovationworks', 'is_quant_target': False,
     'sector': 'nonprofit'},
    {'name': 'Specialisterne', 'ats_token': 'specialisterne', 'is_quant_target': False,
     'sector': 'nonprofit'},
    {'name': 'Spherix Global Insights', 'ats_token': 'spherixglobalinsights', 'is_quant_target': False,
     'sector': 'health'},
    {'name': 'Open Road Integrated Media', 'ats_token': 'openroadmedia', 'is_quant_target': False,
     'sector': 'media'},
    {'name': 'ZGF Architects', 'ats_token': 'zgfarchitects', 'is_quant_target': False},
    {'name': 'Emerging Tech', 'ats_token': 'emergingtech', 'is_quant_target': False},
    {'name': 'Stellar Science', 'ats_token': 'stellarscience', 'is_quant_target': False},
    {'name': 'SimIS', 'ats_token': 'simisinc', 'is_quant_target': False},
    {'name': 'Black Cape', 'ats_token': 'blackcape', 'is_quant_target': False},
    {'name': 'CloudFit Software', 'ats_token': 'cloudfitsoftware', 'is_quant_target': False},
    {'name': 'Geo Owl', 'ats_token': 'geoowl', 'is_quant_target': False},
    {'name': 'IntelliGenesis', 'ats_token': 'intelligenesis', 'is_quant_target': False},
    {'name': 'Innovative Systems', 'ats_token': 'innovativesystems', 'is_quant_target': False},
    {'name': 'Naver U.Hub', 'ats_token': 'naveruhubinc', 'is_quant_target': False},
    {'name': 'Prospect Equities', 'ats_token': 'prospectequities', 'is_quant_target': False},
    {'name': 'Gulf Management', 'ats_token': 'gulfmanagement', 'is_quant_target': False},
]

# --- end sector seeds ---
